async function run() {
  throw "Error2";
}
run();
